def analyze_raw_text_prompt(raw_text: str) -> str:
    return (
        f"<objective>"
        f"Você é um especialista em análise de e-mails, "
        f"seu objetivo é classificar o conteúdo do e-mail "
        f"e determinar se ele é produtivo ou improdutivo "
        f"com base no texto fornecido. "
        f"Um e-mail é considerado 'Produtivo' quando:"
        f" 1. Tem um objetivo claro e direto — como uma solicitação de ação, envio de documento, "
        f"    atualização de processo ou dúvida relevante."
        f" 2. Está relacionado a processos internos da empresa — como atendimento ao cliente, "
        f"    operações financeiras, compliance, RH, jurídico, TI, etc."
        f" 3. Exige uma ação concreta ou tomada de decisão por parte da equipe."
        f" 4. Contém linguagem profissional e conteúdo relevante ao contexto do negócio."
        f" 5. Pode conter anexos técnicos/documentais (PDF, planilhas, contratos, etc.)."
        f"Um e-mail é considerado 'Improdutivo' quando:"
        f" 1. Contém apenas saudações ou mensagens genéricas (ex: 'bom dia', 'feliz natal')."
        f" 2. Não possui conteúdo informativo útil ou relacionado aos processos da empresa."
        f" 3. Está em tom casual ou fora de contexto corporativo."
        f" 4. É repetitivo, sem trazer novos dados, ou é uma confirmação automática ('recebido')."
        f"</objective>"
        f""
        f"<rules>"
        f"1. Retorne no campo \"type\" se ele é 'Produtivo' ou 'Improdutivo'."
        f"2. O campo 'subject' deve conter o assunto do e-mail, entre 5 a 7 palavras."
        f"3. O campo 'text' deve conter um resumo do conteúdo do e-mail, entre 15 a 20 palavras."
        f"4. O campo 'timestamp' é opcional e deve conter a data e hora do e-mail "
        f"   no formato ISO 8601 (YYYY-MM-DDTHH:MM:SSZ)."
        f"5. Se o e-mail não contiver informações suficientes para determinar a classificação, "
        f"   retorne 'Improdutivo' e preencha os outros campos subject e text com 'N/A'."
        f"6. Se o e-mail contiver informações suficientes, preencha os campos de forma consistente."
        f"7. Se o e-mail não contiver timestamp, não inclua o campo na resposta final."
        f"</rules>"
        f""
        f"<email_content>"
        f"{raw_text}"
        f"</email_content>"
        f""
        f"<response_format>"
        "{\n"
        f'   "subject": "valor",\n'
        f'   "type": "Produtivo" ou "Improdutivo",\n'
        f'   "text": "valor",\n'
        f'   "timestamp": "YYYY-MM-DDTHH:MM:SSZ" (opcional)\n'
        "}"
        f"</response_format>"
    )
